version: '1.4'
services:
  eventsapp-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - 1401:1433
    expose:
      - 1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "QWElkj132!" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - eventsappnet

  eventsapp-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - RABBITMQ_CONNECTIONSTRING=${RABBITMQ_CONNECTIONSTRING}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    ports:
      - 7294:7294
    networks:
      - eventsappnet
    links:
      - eventsapp-sql
    depends_on:
      eventsapp-sql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  eventsapp-subscriber:
    restart: on-failure
    build:
      context: .
      dockerfile: eventsApp.Subscriber/Dockerfile
    environment:
      - RABBITMQ_CONNECTIONSTRING=${RABBITMQ_CONNECTIONSTRING}
      - MAIL=${MAIL}
      - MAIL_PASS=${MAIL_PASS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - eventsappnet

  dobavljac-ulaznica:
    restart: on-failure
    build:
      context: .
      dockerfile: eventsApp.DobavljacUlaznica/Dockerfile
    environment:
      - RABBITMQ_CONNECTIONSTRING=${RABBITMQ_CONNECTIONSTRING}
      - KARTE_API_URL=${KARTE_API_URL}
      - DOBAVLJAC_USERNAME=${DOBAVLJAC_USERNAME}
      - DOBAVLJAC_PASSWORD=${DOBAVLJAC_PASSWORD}
    stdin_open: true
    tty: true
    container_name: dobavljac-ulaznica
    links:
      - eventsapp-api
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - eventsappnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - eventsappnet
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  eventsappnet:
    driver: bridge      