// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eventsApp.Services.Database;

#nullable disable

namespace eventsApp.Services.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20240720133812_EventProgramSlika")]
    partial class EventProgramSlika
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eventsApp.Services.Database.Dobavljaci", b =>
                {
                    b.Property<int>("DobavljacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DobavljacID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DobavljacId"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Fax")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Web")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DobavljacId");

                    b.ToTable("Dobavljaci", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.Dogadjaji", b =>
                {
                    b.Property<int>("DogadjajId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DogadjajID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DogadjajId"));

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime");

                    b.Property<int?>("DobavljacId")
                        .HasColumnType("int")
                        .HasColumnName("DobavljacID");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int")
                        .HasColumnName("KategorijaID");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("LokacijaSlika")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Naslovna")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organizator")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("PodkategorijaId")
                        .HasColumnType("int")
                        .HasColumnName("PodkategorijaID");

                    b.Property<string>("Program")
                        .HasColumnType("text");

                    b.Property<byte[]>("ProgramSlika")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DogadjajId");

                    b.HasIndex("DobavljacId");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Dogadjaji", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.HistorijaPregledum", b =>
                {
                    b.Property<int>("PregledId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PregledID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PregledId"));

                    b.Property<int>("DogadjajId")
                        .HasColumnType("int")
                        .HasColumnName("DogadjajID");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime");

                    b.HasKey("PregledId");

                    b.HasIndex("DogadjajId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("HistorijaPregleda");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Karte", b =>
                {
                    b.Property<int>("KartaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KartaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KartaId"));

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sjediste")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("TipKarteId")
                        .HasColumnType("int")
                        .HasColumnName("TipKarteID");

                    b.HasKey("KartaId");

                    b.HasIndex("TipKarteId");

                    b.ToTable("Karte", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.Kategorije", b =>
                {
                    b.Property<int>("KategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KategorijaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("Slika")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("KategorijaId");

                    b.ToTable("Kategorije", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.Komentari", b =>
                {
                    b.Property<int>("KomentarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KomentarID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KomentarId"));

                    b.Property<int>("DogadjajId")
                        .HasColumnType("int")
                        .HasColumnName("DogadjajID");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime");

                    b.HasKey("KomentarId");

                    b.HasIndex("DogadjajId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Komentari", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.Korisnici", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("Drzava")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LozinkaSalt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool?>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KorisnikId");

                    b.HasIndex(new[] { "Email" }, "CS_Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex(new[] { "KorisnickoIme" }, "CS_KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnici", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.KorisniciUloge", b =>
                {
                    b.Property<int>("KorisnikUlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KorisnikUlogaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikUlogaId"));

                    b.Property<DateTime>("DatumIzmjene")
                        .HasColumnType("datetime");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int")
                        .HasColumnName("UlogaID");

                    b.HasKey("KorisnikUlogaId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisniciUloge", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.NarudzbaStavke", b =>
                {
                    b.Property<int>("NarudzbaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NarudzbaStavkaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NarudzbaStavkaId"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("NarudzbaId")
                        .HasColumnType("int")
                        .HasColumnName("NarudzbaID");

                    b.Property<int>("TipKarteId")
                        .HasColumnType("int")
                        .HasColumnName("TipKarteID");

                    b.HasKey("NarudzbaStavkaId");

                    b.HasIndex("NarudzbaId");

                    b.HasIndex("TipKarteId");

                    b.ToTable("NarudzbaStavke", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.Narudzbe", b =>
                {
                    b.Property<int>("NarudzbaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NarudzbaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NarudzbaId"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BrojNarudzbe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime");

                    b.Property<string>("Drzava")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("IznosBezPdv")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("IznosBezPDV");

                    b.Property<decimal>("IznosSaPdv")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("IznosSaPDV");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    b.Property<bool?>("Otkazano")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NarudzbaId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Narudzbe", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.Podkategorije", b =>
                {
                    b.Property<int>("PodkategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PodkategorijaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PodkategorijaId"));

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int")
                        .HasColumnName("KategorijaID");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PodkategorijaId");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Podkategorije", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.Pracenje", b =>
                {
                    b.Property<int>("PracenjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PracenjeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PracenjeId"));

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int")
                        .HasColumnName("KategorijaID");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime");

                    b.HasKey("PracenjeId");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Pracenje", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.Saving", b =>
                {
                    b.Property<int>("SaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SaveID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaveId"));

                    b.Property<int>("DogadjajId")
                        .HasColumnType("int")
                        .HasColumnName("DogadjajID");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime");

                    b.HasKey("SaveId");

                    b.HasIndex("DogadjajId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Saving", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.Slike", b =>
                {
                    b.Property<int>("SlikaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SlikaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlikaId"));

                    b.Property<int>("DogadjajId")
                        .HasColumnType("int")
                        .HasColumnName("DogadjajID");

                    b.Property<string>("Opis")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Slika")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("SlikaId");

                    b.HasIndex("DogadjajId");

                    b.ToTable("Slike", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.TipKarte", b =>
                {
                    b.Property<int>("TipKarteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipKarteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipKarteId"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("DogadjajId")
                        .HasColumnType("int")
                        .HasColumnName("DogadjajID");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stanje")
                        .HasColumnType("int");

                    b.HasKey("TipKarteId");

                    b.HasIndex("DogadjajId");

                    b.ToTable("TipKarte", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.UlazStavke", b =>
                {
                    b.Property<int>("UlazStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UlazStavkaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlazStavkaId"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte[]>("KarteInfo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("TipKarteId")
                        .HasColumnType("int")
                        .HasColumnName("TipKarteID");

                    b.Property<int>("UlazId")
                        .HasColumnType("int")
                        .HasColumnName("UlazID");

                    b.HasKey("UlazStavkaId");

                    b.HasIndex("TipKarteId");

                    b.HasIndex("UlazId");

                    b.ToTable("UlazStavke", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.Ulazi", b =>
                {
                    b.Property<int>("UlazId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UlazID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlazId"));

                    b.Property<string>("BrojFakture")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime");

                    b.Property<int>("DobavljacId")
                        .HasColumnType("int")
                        .HasColumnName("DobavljacID");

                    b.Property<decimal>("IznosRacuna")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Pdv")
                        .HasColumnType("numeric(18, 2)")
                        .HasColumnName("PDV");

                    b.HasKey("UlazId");

                    b.HasIndex("DobavljacId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Ulazi", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.Uloge", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UlogaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UlogaId");

                    b.ToTable("Uloge", (string)null);
                });

            modelBuilder.Entity("eventsApp.Services.Database.Dogadjaji", b =>
                {
                    b.HasOne("eventsApp.Services.Database.Dobavljaci", "Dobavljac")
                        .WithMany("Dogadjajis")
                        .HasForeignKey("DobavljacId")
                        .HasConstraintName("FK_Dogadjaji_Dobavljaci");

                    b.HasOne("eventsApp.Services.Database.Kategorije", "Kategorija")
                        .WithMany("Dogadjajis")
                        .HasForeignKey("KategorijaId")
                        .IsRequired()
                        .HasConstraintName("FK_Dogadjaji_Kategorije");

                    b.Navigation("Dobavljac");

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("eventsApp.Services.Database.HistorijaPregledum", b =>
                {
                    b.HasOne("eventsApp.Services.Database.Dogadjaji", "Dogadjaj")
                        .WithMany("HistorijaPregleda")
                        .HasForeignKey("DogadjajId")
                        .IsRequired()
                        .HasConstraintName("FK_HistorijaPregleda_Dogadjaji");

                    b.HasOne("eventsApp.Services.Database.Korisnici", "Korisnik")
                        .WithMany("HistorijaPregleda")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_HistorijaPregleda_Korisnici");

                    b.Navigation("Dogadjaj");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Karte", b =>
                {
                    b.HasOne("eventsApp.Services.Database.TipKarte", "TipKarte")
                        .WithMany("Kartes")
                        .HasForeignKey("TipKarteId")
                        .HasConstraintName("FK_Karte_TipKarte");

                    b.Navigation("TipKarte");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Komentari", b =>
                {
                    b.HasOne("eventsApp.Services.Database.Dogadjaji", "Dogadjaj")
                        .WithMany("Komentaris")
                        .HasForeignKey("DogadjajId")
                        .IsRequired()
                        .HasConstraintName("FK_Komentari_Dogadjaji");

                    b.HasOne("eventsApp.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Komentaris")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Komentari_Korisnici");

                    b.Navigation("Dogadjaj");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eventsApp.Services.Database.KorisniciUloge", b =>
                {
                    b.HasOne("eventsApp.Services.Database.Korisnici", "Korisnik")
                        .WithMany("KorisniciUloges")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_KorisniciUloge_Korisnici");

                    b.HasOne("eventsApp.Services.Database.Uloge", "Uloga")
                        .WithMany("KorisniciUloges")
                        .HasForeignKey("UlogaId")
                        .IsRequired()
                        .HasConstraintName("FK_KorisniciUloge_Uloge");

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eventsApp.Services.Database.NarudzbaStavke", b =>
                {
                    b.HasOne("eventsApp.Services.Database.Narudzbe", "Narudzba")
                        .WithMany("NarudzbaStavkes")
                        .HasForeignKey("NarudzbaId")
                        .IsRequired()
                        .HasConstraintName("FK_NarudzbaStavke_Narudzbe");

                    b.HasOne("eventsApp.Services.Database.TipKarte", "TipKarte")
                        .WithMany("NarudzbaStavkes")
                        .HasForeignKey("TipKarteId")
                        .IsRequired()
                        .HasConstraintName("FK_NarudzbaStavke_TipKarte");

                    b.Navigation("Narudzba");

                    b.Navigation("TipKarte");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Narudzbe", b =>
                {
                    b.HasOne("eventsApp.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Narudzbes")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Narudzbe_Korisnici");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Podkategorije", b =>
                {
                    b.HasOne("eventsApp.Services.Database.Kategorije", "Kategorija")
                        .WithMany("Podkategorijes")
                        .HasForeignKey("KategorijaId")
                        .IsRequired()
                        .HasConstraintName("FK_Podkategorije_Kategorije");

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Pracenje", b =>
                {
                    b.HasOne("eventsApp.Services.Database.Kategorije", "Kategorija")
                        .WithMany("Pracenjes")
                        .HasForeignKey("KategorijaId")
                        .IsRequired()
                        .HasConstraintName("FK_Pracenje_Kategorije");

                    b.HasOne("eventsApp.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Pracenjes")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Pracenje_Korisnici");

                    b.Navigation("Kategorija");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Saving", b =>
                {
                    b.HasOne("eventsApp.Services.Database.Dogadjaji", "Dogadjaj")
                        .WithMany("Savings")
                        .HasForeignKey("DogadjajId")
                        .IsRequired()
                        .HasConstraintName("FK_Saving_Dogadjaji");

                    b.HasOne("eventsApp.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Savings")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Saving_Korisnici");

                    b.Navigation("Dogadjaj");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Slike", b =>
                {
                    b.HasOne("eventsApp.Services.Database.Dogadjaji", "Dogadjaj")
                        .WithMany("Slikes")
                        .HasForeignKey("DogadjajId")
                        .IsRequired()
                        .HasConstraintName("FK_Slike_Dogadjaji");

                    b.Navigation("Dogadjaj");
                });

            modelBuilder.Entity("eventsApp.Services.Database.TipKarte", b =>
                {
                    b.HasOne("eventsApp.Services.Database.Dogadjaji", "Dogadjaj")
                        .WithMany("TipKartes")
                        .HasForeignKey("DogadjajId")
                        .HasConstraintName("FK_TipKarte_Dogadjaji");

                    b.Navigation("Dogadjaj");
                });

            modelBuilder.Entity("eventsApp.Services.Database.UlazStavke", b =>
                {
                    b.HasOne("eventsApp.Services.Database.TipKarte", "TipKarte")
                        .WithMany("UlazStavkes")
                        .HasForeignKey("TipKarteId")
                        .IsRequired()
                        .HasConstraintName("FK_UlazStavke_TipKarte");

                    b.HasOne("eventsApp.Services.Database.Ulazi", "Ulaz")
                        .WithMany("UlazStavkes")
                        .HasForeignKey("UlazId")
                        .IsRequired()
                        .HasConstraintName("FK_UlazStavke_Ulazi");

                    b.Navigation("TipKarte");

                    b.Navigation("Ulaz");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Ulazi", b =>
                {
                    b.HasOne("eventsApp.Services.Database.Dobavljaci", "Dobavljac")
                        .WithMany("Ulazis")
                        .HasForeignKey("DobavljacId")
                        .IsRequired()
                        .HasConstraintName("FK_Ulazi_Dobavljaci");

                    b.HasOne("eventsApp.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Ulazis")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Ulazi_Korisnici");

                    b.Navigation("Dobavljac");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Dobavljaci", b =>
                {
                    b.Navigation("Dogadjajis");

                    b.Navigation("Ulazis");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Dogadjaji", b =>
                {
                    b.Navigation("HistorijaPregleda");

                    b.Navigation("Komentaris");

                    b.Navigation("Savings");

                    b.Navigation("Slikes");

                    b.Navigation("TipKartes");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Kategorije", b =>
                {
                    b.Navigation("Dogadjajis");

                    b.Navigation("Podkategorijes");

                    b.Navigation("Pracenjes");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Korisnici", b =>
                {
                    b.Navigation("HistorijaPregleda");

                    b.Navigation("Komentaris");

                    b.Navigation("KorisniciUloges");

                    b.Navigation("Narudzbes");

                    b.Navigation("Pracenjes");

                    b.Navigation("Savings");

                    b.Navigation("Ulazis");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Narudzbe", b =>
                {
                    b.Navigation("NarudzbaStavkes");
                });

            modelBuilder.Entity("eventsApp.Services.Database.TipKarte", b =>
                {
                    b.Navigation("Kartes");

                    b.Navigation("NarudzbaStavkes");

                    b.Navigation("UlazStavkes");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Ulazi", b =>
                {
                    b.Navigation("UlazStavkes");
                });

            modelBuilder.Entity("eventsApp.Services.Database.Uloge", b =>
                {
                    b.Navigation("KorisniciUloges");
                });
#pragma warning restore 612, 618
        }
    }
}
